Informe o numero de linhas da matriz A: 2000
Informe o numero de colunas da matriz A: 2000
Informe o numero de colunas da matriz B: 2000
Iniciando multiplicacaao de matrizes com 6 threads...
Thread 5 iniciando multiplicacao...
Thread 0 iniciando multiplicacao...
Thread 3 iniciando multiplicacao...
Thread 2 iniciando multiplicacao...
Thread 4 iniciando multiplicacao...
Thread 1 iniciando multiplicacao...

Tempo de execucao paralelo: 9.492238 segundos


Informe o numero de linhas da matriz A: 4000
Informe o numero de colunas da matriz A: 4000
Informe o numero de colunas da matriz B: 4000
Iniciando multiplicacaao de matrizes com 6 threads...
Thread 4 iniciando multiplicacao...
Thread 1 iniciando multiplicacao...
Thread 5 iniciando multiplicacao...
Thread 2 iniciando multiplicacao...
Thread 3 iniciando multiplicacao...
Thread 0 iniciando multiplicacao...

Tempo de execucao paralelo: 88.708935 segundos


Informe o numero de linhas da matriz A: 6000     
Informe o numero de colunas da matriz A: 6000
Informe o numero de colunas da matriz B: 6000
Iniciando multiplicacaao de matrizes com 6 threads...
Thread 2 iniciando multiplicacao...
Thread 4 iniciando multiplicacao...
Thread 1 iniciando multiplicacao...
Thread 5 iniciando multiplicacao...
Thread 3 iniciando multiplicacao...
Thread 0 iniciando multiplicacao...

Tempo de execucao paralelo: 428.329915 segundos


Informe o numero de linhas da matriz A: 8000     
Informe o numero de colunas da matriz A: 8000
Informe o numero de colunas da matriz B: 8000
Iniciando multiplicacaao de matrizes com 6 threads...
Thread 2 iniciando multiplicacao...
Thread 4 iniciando multiplicacao...
Thread 1 iniciando multiplicacao...
Thread 5 iniciando multiplicacao...
Thread 3 iniciando multiplicacao...
Thread 0 iniciando multiplicacao...

Tempo de execucao paralelo: 1252.623956 segundos
