Informe o numero de linhas da matriz A: 2000
Informe o numero de colunas da matriz A: 2000
Informe o numero de colunas da matriz B: 2000
Iniciando multiplicacaao de matrizes com 8 threads...
Thread 6 iniciando multiplicacao...
Thread 4 iniciando multiplicacao...
Thread 7 iniciando multiplicacao...
Thread 1 iniciando multiplicacao...
Thread 0 iniciando multiplicacao...
Thread 3 iniciando multiplicacao...
Thread 2 iniciando multiplicacao...
Thread 5 iniciando multiplicacao...

Tempo de execucao paralelo: 8.712088 segundos


Informe o numero de linhas da matriz A: 4000
Informe o numero de colunas da matriz A: 4000
Informe o numero de colunas da matriz B: 4000
Iniciando multiplicacaao de matrizes com 8 threads...
Thread 3 iniciando multiplicacao...
Thread 7 iniciando multiplicacao...
Thread 4 iniciando multiplicacao...
Thread 2 iniciando multiplicacao...
Thread 0 iniciando multiplicacao...
Thread 6 iniciando multiplicacao...
Thread 5 iniciando multiplicacao...
Thread 1 iniciando multiplicacao...

Tempo de execucao paralelo: 82.986512 segundos


Informe o numero de linhas da matriz A: 6000
Informe o numero de colunas da matriz A: 6000
Informe o numero de colunas da matriz B: 6000
Iniciando multiplicacaao de matrizes com 8 threads...
Thread 5 iniciando multiplicacao...
Thread 2 iniciando multiplicacao...
Thread 7 iniciando multiplicacao...
Thread 6 iniciando multiplicacao...
Thread 1 iniciando multiplicacao...
Thread 4 iniciando multiplicacao...
Thread 0 iniciando multiplicacao...
Thread 3 iniciando multiplicacao...

Tempo de execucao paralelo: 348.147686 segundos


Informe o numero de linhas da matriz A: 8000
Informe o numero de colunas da matriz A: 8000
Informe o numero de colunas da matriz B: 8000
Iniciando multiplicacaao de matrizes com 8 threads...
Thread 5 iniciando multiplicacao...
Thread 2 iniciando multiplicacao...
Thread 7 iniciando multiplicacao...
Thread 6 iniciando multiplicacao...
Thread 1 iniciando multiplicacao...
Thread 4 iniciando multiplicacao...
Thread 0 iniciando multiplicacao...
Thread 3 iniciando multiplicacao...

Tempo de execucao paralelo: 1018.194863 segundos
