Informe o numero de linhas da matriz A: 2000
Informe o numero de colunas da matriz A: 2000
Informe o numero de colunas da matriz B: 2000
Iniciando multiplicacaao de matrizes com 4 threads...
Thread 1 iniciando multiplicacao...
Thread 3 iniciando multiplicacao...
Thread 0 iniciando multiplicacao...
Thread 2 iniciando multiplicacao...

Tempo de execucao paralelo: 7.245343 segundos


Informe o numero de linhas da matriz A: 4000
Informe o numero de colunas da matriz A: 4000
Informe o numero de colunas da matriz B: 4000
Iniciando multiplicacaao de matrizes com 4 threads...
Thread 3 iniciando multiplicacao...
Thread 1 iniciando multiplicacao...
Thread 2 iniciando multiplicacao...
Thread 0 iniciando multiplicacao...

Tempo de execucao paralelo: 71.763566 segundos


Informe o numero de linhas da matriz A: 6000
Informe o numero de colunas da matriz A: 6000
Informe o numero de colunas da matriz B: 6000
Iniciando multiplicacaao de matrizes com 4 threads...
Thread 1 iniciando multiplicacao...
Thread 2 iniciando multiplicacao...
Thread 0 iniciando multiplicacao...
Thread 3 iniciando multiplicacao...

Tempo de execucao paralelo: 361.960991 segundos


Informe o numero de linhas da matriz A: 8000
Informe o numero de colunas da matriz A: 8000
Informe o numero de colunas da matriz B: 8000
Iniciando multiplicacaao de matrizes com 4 threads...
Thread 2 iniciando multiplicacao...
Thread 1 iniciando multiplicacao...
Thread 0 iniciando multiplicacao...
Thread 3 iniciando multiplicacao...

Tempo de execucao paralelo: 1058.549663 segundos